version: "3"
services:
  httpd2-web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ${PROJECT_PATH}/:/var/www/:cached
      # - ./php.ini:/usr/local/etc/php/php.ini
